# This file contains the Kubernetes deployment and service definitions for a MongoDB CRUD application with minimalistic setup.
# It includes two deployments: one for the CRUD application and another for the MongoDB database.
# The deployment for the CRUD application uses the latest version of the `jjayaraman/mongo-crud` image and exposes port 8080.
# The deployment for the MongoDB database uses the latest version of the `mongo` image and exposes port 27017.
# The service for the CRUD application exposes port 8080 and is accessible from outside the cluster.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crud-app
  name: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/jaydb
          image: jjayaraman/mongo-crud:latest
          name: mongo-crud
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crud-app
  name: crud-app
spec:
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: crud-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
    - name: 27017-27017
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
